language: node_js

node_js:
  - 8

script:
  - yarn test --config videoRecording=true --record --key $CYPRESS_DASHBOARD_KEY

cache: 
  yarn: true
  directories:
  - node_modules

notifications:
  email:
    on_success: change
    on_failure: always